# Generated by Django 4.2 on 2023-04-26 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', '남성'), ('Female', '여성')], max_length=6, null=True),
        ),
    ]
